### ISSUE TITLE
WPF App + Storage.Net with NetBox causes CA1724 warning from FxCopAnalyzer

### ISSUE THREAD

**Issue by katdti** [aloneguid/netbox#11]
Recreation:
- Create an WPF app using standard visual studio template
- Add Storage.Net nuget package
- Add Microsoft.CodeAnalysis.FxCopAnalyzer nuget pacakge
- Build

Result:
> Warning	CA1724	The type name App conflicts in whole or in part with the namespace name 'NetBox.Terminal.App'. Change either name to eliminate the conflict.	

Warning can be disabled - so it is not a big problem.

Question:
- That is the purpose of NetBox.Terminal.App?
- Would it be better with seperate nuget package for the NetBox.Terminal.App?

/Regards

**Comment by aloneguid** [comment]
Please see the latest readme. It's all resolved ;)
